### ISSUE TITLE
the data hasn't been updated for 8 days

### ISSUE THREAD

**Issue by lunaticalq** [vigovlugt/draftgap#6]
like the title, the app says last time it updated was 8 days ago
![image](https://github.com/vigovlugt/draftgap/assets/146641143/be50594d-f736-4ef1-a384-97166949f381)

**Comment by MisterBored** [comment]
The API for LoLalytics has been taken down.

"As the transition to the new version LoLalytics has gone relatively smoothly I've taken the classic version of the site and its associated APIs offline. The new version of the site is server side rather than client side rendered which negates the need for a public API. Having a single version of the site reduces the workload and costs significantly which I've maintained for the last 6 months during its development. There are a lot more features coming soon...."

**Comment by WRLeal** [comment]
Going forward will DraftGap use another API? love the app guys 👍

**Comment by vigovlugt** [comment]
For now I have implemented a temporary fix in the meantime, updating the data that is changing the most.
The people at LoLalytics have announced they are working on a new public API, so when that becomes available, the DraftGap data will be updated using that.
